stages:
  - build
  - check

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  PYTHON_IMAGE: python:3.10
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  CODE: "app tests tools"

build:
  image: $PYTHON_IMAGE
  stage: build
  artifacts:
    paths:
      - .cache/pip
      - .venv/
      - .env
  script:
    - make env
    - make venv
    - make install

lint:
  image: $PYTHON_IMAGE
  stage: check
  script:
    - make lint

test:
  image: $PYTHON_IMAGE
  stage: check
  variables:
    POSTGRES_DB: data
    POSTGRES_USER: pguser
    POSTGRES_PASSWORD: pgpswd
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
  services:
    - name: postgres:14.5
  before_script:
    - printf "POSTGRES_HOST=postgres\n" >> .env
  script:
    - make test-mp
