image: python:3.10

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  CODE: "app tests tools"

cache:
  paths:
    - .cache/pip
    - .venv/

before_script:
  - make venv
  - make install

stages:
  - lint
  - test

lint:
  stage: lint
  script:
    - make env
    - make lint

test:
  stage: test
  variables:
    POSTGRES_DB: data
    POSTGRES_USER: pguser
    POSTGRES_PASSWORD: pgpswd
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
  services:
    - name: postgres:14.5
  script:
    - make env
    - make test-mp
