scheduler:
  ping:
    trigger: interval
    minutes: 1
    config:
      send_logs: false
  db_dump:
    trigger: cron
    hour: 3
    config:
      send_logs: true
#  contest_register:
#    trigger: interval
#    minutes: 10
#    config:
#      send_logs: true
  contest_register_group:
    trigger: interval
    minutes: 10
    config:
      send_logs: true
  update_results:
    trigger: interval
    hours: 1
    config:
      send_logs: true