version: '3.9'

services:
  app:
    container_name: app
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    volumes:
      - ./logs:/opt/app/logs
    ports:
      - "8090:8090"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - app_network

  scheduler:
    container_name: scheduler
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    volumes:
      - ./logs:/opt/app/logs
    command: make up-scheduler
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - app_network

  postgres:
    container_name: postgres
    image: postgres:14.5
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    env_file:
      - .env
    volumes:
       - db-data:/var/lib/postgresql/data
       - ./db/postgres.conf:/etc/postgresql/postgresql.conf
       - ./db/pg_hba.conf:/etc/postgresql/pg_hba.conf
       - ./db/slave_pgdata:/slave_pgdata
       - ./db/init_master.sh:/init_master.sh
       - ./db/init_master.sql:/init_master.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - app_network

  postgres_slave:
    container_name: postgres_slave
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_MASTER_SERVICE_HOST: postgres
    env_file:
      - .env
    volumes:
      - ./db/postgres.conf:/etc/postgresql/postgresql.conf
      - ./db/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./db/init_slave.sh:/init_slave.sh
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - app_network
    depends_on:
      - postgres

  nginx:
    container_name: nginx
    image: nginx:1.23.1
    env_file:
      - .env
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx/
    ports:
      - "80:80"
    networks:
      - app_network

  redis:
    image: 'redis:7'
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - app_network

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: make up-celery-worker
    env_file:
      - .env
    volumes:
      - ./logs:/opt/app/logs
    depends_on:
      - app
      - redis
      - postgres
    restart: unless-stopped
    networks:
      - app_network

  celery_dashboard:
    container_name: celery_dashboard
    build:
      context: .
      dockerfile: Dockerfile
    command: make up-celery-dashboard
    ports:
      - 5556:5555
    env_file:
      - .env
    depends_on:
      - app
      - redis
      - celery_worker
    restart: unless-stopped
    networks:
      - app_network

  loki:
    container_name: loki
    image: grafana/loki:2.7.3
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app_network

  promtail:
    container_name: promtail
    image: grafana/promtail:2.7.3
    volumes:
      - ./logs:/home/logs
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - app_network

  grafana:
    container_name: grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=false
    env_file:
      - .env
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:9.4.3
    ports:
      - "3000:3000"
    networks:
      - app_network


networks:
  app_network:
    driver: bridge

volumes:
  db-data:
