server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  pipeline_stages:
  - json:
      expressions:
        text: text
        record: record
  - json:
      expressions:
        exception: exception
        extra:
        file:
        function: function
        level:
        line: line
        message: message
        module: module
        name: name
        process:
        thread:
        time:
      source: record
  - json:
      expressions:
        uuid: uuid
        student:
        course:
        contest:
        task:
        submission:
        request:
      source: extra
  - json:
      expressions:
        request_id: id
        request_method: method
        request_scheme: scheme
        request_http_version: http_version
        request_path: path
        request_status_code: status_code
        request_client: client
      source: request
  - json:
      expressions:
        student_id: id
        student_contest_login: contest_login
        student_department: department
      source: student
  - json:
      expressions:
        course_id: id
        course_short_name: short_name
      source: course
  - json:
      expressions:
        contest_id: id
        yandex_contest_id: yandex_contest_id
      source: contest
  - json:
      expressions:
        task_id: id
        yandex_task_id: yandex_task_id
      source: task
  - json:
      expressions:
        submission_id: id
        submission_author_id: author_id
      source: submission
  - json:
      expressions:
        file_name: name
        file_path: path
      source: file
  - json:
      expressions:
        level_name: name
      source: level
  - json:
      expressions:
        process_id: id
        process_name: name
      source: process
  - json:
      expressions:
        thread_id: id
        thread_name: name
      source: thread
  - json:
      expressions:
        time_repr: repr
        timestamp: timestamp
      source: time
  - labels:
      function:
      module:
      name:
      file_name:
      file_path:
      level_name:
      process_name:
      thread_name:
      request_method:
      request_scheme:
      request_http_version:
      request_path:
      request_status_code:
      course_id:
      course_short_name:
      contest_id:
      yandex_contest_id:
  - timestamp:
      source: time_repr
      format: '2023-02-24 13:02:52.705196+00:00'
  static_configs:
  - targets:
      - localhost
    labels:
      job: applogs
      __path__: /home/logs/*log
