{
 "title": "New dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 1, "y": 0 },
   "targets": [
    {
     "expr": "sum by(response_status_code) (rate({application=\"app\", log_type=\"response\"} [1m]))"
    }
   ]
  },
  {
   "title": "Scheduler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by(job_name) (rate({application=\"scheduler\", log_type=\"scheduler_start\"} [1h]))"
    }
   ]
  },
  {
   "title": "Celery Task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg by(celery_task_name) (rate({application=\"worker\", log_type=\"celery_task_start\"} [1h]))"
    }
   ]
  }
 ]
}