#!/bin/bash
set -e

rm -rf /var/lib/postgresql/data/*
PGPASSWORD=$POSTGRES_REPLICATOR_PASSWORD pg_basebackup --host=postgres --username=replicator --pgdata=/var/lib/postgresql/data/pgdata --wal-method=stream --write-recovery-conf --progress --format=plain
echo "# Do not edit this file manually!
# It will be overwritten by the ALTER SYSTEM command.
primary_conninfo = 'host=$POSTGRES_HOST port=$POSTGRES_PORT user=replicator password=$POSTGRES_REPLICATOR_PASSWORD'
" >  /var/lib/postgresql/data/pgdata/postgresql.auto.conf
